# Site Info
title: Adela Inside
tagline: 'Adela Inside'
description: 'Dev Blog for Adela'
baseurl: ''
url: "https://love-adelar.github.io"
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/category/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: ADELA
  description: <strong>ADELA</strong>, </br> Loves Art of Programming
  gravatar: 2c87a3ffdb44740984a28ce6dc23e870 # md5 hash of your email address
  contact:
  linkedin:  
  github:    https://github.com/love-adelar
  facebook:  https://www.facebook.com/jeong.adela.7
  twitter:   https://twitter.com/love_ade1a
  email:     love.adelar@gmail.com
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Category:           
    - '/category/'
    - { Python: '/category/python/' }
    - { Tags: '/category/tags/' }
    - { TIL: '/category/til/' }
    - { Inside: '/category/inside/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://love-adelar.github.io/'

# Where are tags and categories displayed
python_page: '/category/python'
tag_page: '/category/tags/'
til_page: '/category/til/'

hero:
  image: /public/img/jeju_profile.jpg
  caption: Adela

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: # leave blank if you don't want google analytics
disqus_short_name: 'loveadelar' # leave blank if you don't want disqus

