# Site settings
title: Adela Inside
subtitle: Adela's Dev Blog
url: "https://love-adelar.github.io" # the base hostname & protocol for your site
baseurl: ''
description: >
    아델라 인사이드

#  Author Information
author: ADELA
email: love.adelar@gmail.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:

#Build settings
permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Social settings
facebook_url:
github_url: github.com/love-adelar
instagram_url: instagram.com/pro_adela
linkedin_url:
twitter_url: twitter.com/love_ade1a

# Google Analytics Tracking ID goes here:
google_analytics:
  ua:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]

timezone: "Asia/Seoul"